weights: /content/runs/prune_sp=0.01_pc=0.25/pruned_model.pt
cfg: models/yolov5s.yaml
data: /content/data/all.yaml
hyp: /content/data/hyps/hyp.finetune_prune.yaml
epochs: 100
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: AdamW
sync_bn: false
workers: 8
project: runs/train
name: prune_sp=0.01_pc=0.25_ft
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
bn_sparsity: false
sparsity_rate: 0.0001
ft_pruned_model: true
save_dir: runs/train/prune_sp=0.01_pc=0.25_ft
