weights: .
cfg: /content/models/MobileNetv2.yaml
data: ./data/all.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: AdamW
sync_bn: false
workers: 8
project: runs/train
name: basic_useMobileNet_backbone
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
bn_sparsity: false
sparsity_rate: 0.0001
ft_pruned_model: false
save_dir: runs/train/basic_useMobileNet_backbone2
